version: "3.7"
services:
  dbpostgres:
    image: postgres:latest
    #restart: always
    #network_mode: 
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USER=postgres
      - POSTGRES_DB=deepflower
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
  goserver:
    build:
      context: ./goback
      dockerfile: Dockerfile
    depends_on:
      - dbpostgres
    ports:
    - 8787:8787
  web:
    build:
      context: ./vue3front
      dockerfile: Dockerfile
    depends_on:
      - goserver
    ports:
      - 5173:5173
volumes:
  data:



