version: "3.7"
services:
  dbpostgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USER=postgres
      - POSTGRES_DB=deepflower
    ports:
      - "32768:5432"
    volumes:
      - data:/var/lib/postgresql/data
  goserver:
    build:
      context: ./goback
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - dbpostgres
    networks:
      - default
    ports:
    - "8787:8787"
  web:
    build:
      context: ./vue3front
      dockerfile: Dockerfile
    depends_on:
      - goserver
    ports:
      - "5173:5173"
    networks:
      - network-backend
volumes:
  data:



