host: "127.0.0.1"
port: 8787
project_name: "deepflower"

auth:
  cost: 1  # (2 ^ cost)time =  4-31
  signing_key: "somekey"
  token_ttl: 7777 #min

postgres: 
    host: host.docker.internal
    port: 32768
    user: "postgres"
    password: "postgrespw"
    dbname: "deepflower"

telegram:
  token: ""
  boturl: "http://t.me/DeepFlowerbot"
