host: 127.0.0.1 #0.0.0.0
port: 8787
project_name: "deepflower"

auth:
  cost: 1  # (2 ^ cost)time =  4-31
  signing_key: "somekey"
  token_ttl: 7777 #min

postgres: 
    host: 127.0.0.1 #host.docker.internal #dbpostgres(compose)
    port: 32768 # 5432(compose) 32768(some)
    user: "postgres"
    password: "postgrespw"
    dbname: "deepflower"

telegram:
  token: "6237215798:AAHQayrhFO8HAvYSi8uVyv4hOcbhJvVr5ro"
  boturl: "http://t.me/DeepFlowerbot"
  debug: "true"
  buffer: 100



