host: "127.0.0.1"
port: 8787

project_name: "deepflower"

auth:
  hash_salt: "hash_salt"
  signing_key: "signing_key"
  token_ttl: 77777

mongo:
  uri: "mongodb://mongodb:29078"
  name: "deepflowerdb"
  user_collection: "users"

telegram:
  token: ""
  boturl: ""
