host: "127.0.0.1"
port: 8787
project_name: "deepflower"

auth:
  hash_salt: 1234
  signing_key: "somekey"
  token_ttl: 7777 #min

postgres: 
    host: host.docker.internal
    port: 32768
    user: "postgres"
    password: "postgrespw"
    dbname: "deepflower"

telegram:
  token: "6237215798:AAHQayrhFO8HAvYSi8uVyv4hOcbhJvVr5ro"
  boturl: "http://t.me/DeepFlowerbot"
